application: gu-newshack
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_dir: www


skip_files: |
    (node_modules/.*) |
    (_old/.*)